version: '3'

services:

  app:
    build: .
    container_name: app
    restart: always
    command:
      - sh
      - -c
      - "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn cashback.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - '8000:8000'
    links:
      - db
    depends_on:
      - db
    volumes:
      - ".:/app/code"
  db:
    image: mysql:8
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_pagimovel_gestores
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data: