# Generated by Django 3.2.6 on 2021-08-21 14:20

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0002_auto_20210821_1418'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reseller',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='username',
        ),
    ]
