# Generated by Django 3.2.6 on 2021-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='per_cent_cashback',
            field=models.IntegerField(default=0),
        ),
    ]
