# Generated by Django 3.2.6 on 2021-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210821_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cashback',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='per_cent_cashback',
            field=models.IntegerField(),
        ),
    ]
