# Generated by Django 3.2.6 on 2021-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210821_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
